# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bn15uHAQu2i9gnG_a8CgiojSWi2xY4RZ
"""

import pandas as pd

dataset1 = pd.read_csv('/content/diabetic_data.csv')
dataset2 = pd.read_csv('/content/patient_geo.csv')
print(dataset1)
print(dataset2)

result = dataset1.join(dataset2.set_index(["encounter_id", "patient_nbr"]),on=["encounter_id", "patient_nbr"], how="outer",lsuffix="_x",rsuffix="_y",)
print(result)

final_dataset = pd.merge(dataset1, dataset2, how="outer")
print(final_dataset)

X = final_dataset.drop('gender', axis =1)
print(X)

Y = final_dataset['gender'].apply(lambda gender:1 if gender == 'Male' else 0)
print(Y)

join2 = [X,Y]
final_dataset2 = pd.concat(join2,axis=1)
print(final_dataset2)

final_dataset2.columns = final_dataset2.columns.str.upper()
print(final_dataset2)

final_dataset2 = final_dataset2.apply(lambda x: x.str.upper() if x.dtype == "object" else x)  
print(final_dataset2)

final_dataset2.to_excel('joined_dataframe.xlsx')